version: "3.2"

networks:
  ods:
    driver: bridge

services:

  redis:
    image: "redis:alpine"
    container_name: 'redis'
    command: redis-server --requirepass crypto --bind redis --port 6379
    ports:
      - 6379:6379
    networks:
      - ods

  keeper:
    container_name: zero-keeper
    build: "./packages/keeper"
    restart: on-failure
    depends_on: 
      - redis
    links:
      - redis
    networks:
      - ods
  # watcher:
  #   container_name: zero/keeper-watcher
  #   build: "./packages/watcher"
  #   restart: on-failure
  #   depends_on:
  #     - redis-server
  #   links:
  #     - redis-server
  #   networks: 
  #     - ods
volumes:
  redis:
    driver: local
