version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server --bind redis --port 6379
    ports:
      - 6379:6379
    networks:
      - requests
  keeper:
    container_name: "Zero/Keeper Process"
    build: '.'
    restart: on-failure
    networks:
      - requests